# Generated by Django 5.2.17 on 2026-10-02 06:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('account_type', models.CharField(choices=[('asset_receivable', 'Receivable'), ('asset_cash', 'Bank and Cash'), ('asset_current', 'Current Assets'), ('asset_fixed', 'Fixed Assets'), ('liability_payable', 'Payable'), ('liability_current', 'Current Liabilities'), ('equity', 'Equity'), ('income', 'Income'), ('expense_direct_cost', 'Cost of Revenue'), ('expense', 'Expenses')], max_length=32)),
                ('description', models.TextField(blank=True, help_text='Plain-English explanation shown in the UI.')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MoveLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('kind', models.CharField(choices=[('product', 'Product'), ('tax', 'Tax'), ('receivable', 'Receivable'), ('payable', 'Payable'), ('liquidity', 'Bank / Cash'), ('stock', 'Stock Valuation'), ('cogs', 'Cost of Goods Sold'), ('other', 'Other')], default='other', max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('price_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='/', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=16)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('journal_type', models.CharField(choices=[('sale', 'Sales'), ('purchase', 'Purchases'), ('bank', 'Bank'), ('cash', 'Cash'), ('general', 'Miscellaneous')], max_length=16)),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='/', max_length=32)),
                ('move_type', models.CharField(choices=[('entry', 'Journal Entry'), ('out_invoice', 'Customer Invoice'), ('in_invoice', 'Vendor Bill')], default='entry', max_length=16)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('invoice_date_due', models.DateField(blank=True, null=True)),
                ('ref', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancel', 'Cancelled')], default='draft', max_length=16)),
                ('payment_state', models.CharField(choices=[('not_paid', 'Not Paid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='not_paid', max_length=16)),
                ('amount_untaxed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_residual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='accounting.journal')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
