# Generated by Django 5.2.17 on 2026-10-02 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masterdata', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='masterdata.partner'),
        ),
        migrations.AddField(
            model_name='move',
            name='picking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valuation_moves', to='inventory.picking'),
        ),
        migrations.AddField(
            model_name='move',
            name='sale_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.saleorder'),
        ),
        migrations.AddField(
            model_name='moveline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='moveline',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.move'),
        ),
        migrations.AddField(
            model_name='moveline',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.partner'),
        ),
        migrations.AddField(
            model_name='moveline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.product'),
        ),
        migrations.AddField(
            model_name='moveline',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.tax'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.move'),
        ),
        migrations.AddField(
            model_name='payment',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='payment',
            name='move',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_of', to='accounting.move'),
        ),
        migrations.AddField(
            model_name='payment',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='masterdata.partner'),
        ),
    ]
