# Generated by Django 5.2.17 on 2026-10-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('mrp', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valuation_moves', to='mrp.manufacturingorder'),
        ),
        migrations.AddField(
            model_name='move',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('inbound', 'Received from customer'), ('outbound', 'Sent to vendor')], default='inbound', max_length=16),
        ),
    ]
