# Generated by Django 5.2.17 on 2026-10-02 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_move_production_move_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='reversed_entry',
            field=models.ForeignKey(blank=True, help_text='For a credit note: the invoice it corrects.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='accounting.move'),
        ),
        migrations.AlterField(
            model_name='move',
            name='move_type',
            field=models.CharField(choices=[('entry', 'Journal Entry'), ('out_invoice', 'Customer Invoice'), ('out_refund', 'Customer Credit Note'), ('in_invoice', 'Vendor Bill')], default='entry', max_length=16),
        ),
    ]
