import type { Chapter } from './types'

export const fundamentals: Chapter = {
  slug: 'erp-fundamentals',
  number: 1,
  title: 'What is an ERP?',
  department: 'Foundations',
  icon: 'Database',
  color: 'blue',
  minutes: 15,
  summary: 'One shared database that runs every department, so each piece of information is entered once and flows everywhere it is needed.',
  goals: [
    'Explain what an ERP is and the problem it solves',
    'Name the core modules of an SME ERP and what each one does',
    'Understand integration: how one action in one module updates the others',
    'Tell master data from transactional data',
    'Know the main ERP products on the market',
  ],
  intro: [
    'ERP stands for Enterprise Resource Planning. In practice it is one software, built on one shared database, that runs the main departments of a company: sales, purchasing, inventory, manufacturing, accounting, HR and more.',
    'Without an ERP, each department keeps its own tools (spreadsheets, a separate accounting package, emails, paper). The same order is typed three times, the numbers never match, and nobody has an up-to-date picture. These are called "information silos".',
    'With an ERP, data is entered once, at the source, by the person who knows it best (the salesperson enters the order, the warehouse confirms the shipment) and every other department sees it immediately. The accounting entries are generated automatically from those operations.',
  ],
  roles: [
    { name: 'Key user', does: 'An employee who knows a department’s process well and is the reference for the ERP in that team.' },
    { name: 'Functional consultant', does: 'Understands the business processes, configures the ERP to fit them, trains users. (Likely your role.)' },
    { name: 'Technical consultant / developer', does: 'Builds customisations, integrations, reports and data imports.' },
    { name: 'Project manager', does: 'Plans the implementation, manages scope, budget, risks and the client relationship.' },
  ],
  process: [
    {
      title: 'One customer order, through the whole company',
      steps: [
        { label: 'Order entered', doc: 'Sales order', who: 'Salesperson', effect: 'Customer, prices and taxes come from master data' },
        { label: 'Goods reserved & shipped', doc: 'Delivery order', who: 'Warehouse', effect: 'Stock goes down automatically' },
        { label: 'Cost recorded', doc: 'Journal entry', who: 'ERP (automatic)', effect: 'Inventory → Cost of Goods Sold' },
        { label: 'Customer invoiced', doc: 'Invoice', who: 'Accountant', effect: 'Revenue, VAT and receivable recorded' },
        { label: 'Payment received', doc: 'Payment', who: 'Accountant', effect: 'Bank up, receivable cleared' },
        { label: 'Reports updated', doc: 'Dashboards', who: 'Management', effect: 'Sales, stock and profit are live' },
      ],
    },
  ],
  concepts: [
    { term: 'Single source of truth', meaning: 'Every department reads the same customer, product and stock record. There is only one version of each fact.' },
    { term: 'Module', meaning: 'A functional area (Sales, Inventory, Accounting…). Modules are separate screens but share the same database.' },
    { term: 'Integration', meaning: 'An action in one module automatically updates others: shipping goods (Inventory) creates an accounting entry (Accounting).' },
    { term: 'Master data', meaning: 'Information that rarely changes and is reused by many transactions: customers, vendors, products, chart of accounts, employees.' },
    { term: 'Transactional data', meaning: 'Day-to-day events that reference master data: orders, deliveries, invoices, payments, payslips.' },
    { term: 'Document / workflow', meaning: 'ERPs work with documents that move through states (draft → confirmed → done). Each state change can trigger effects elsewhere.' },
    { term: 'Real time', meaning: 'Because everything is in one database, reports reflect operations immediately, not at month-end.' },
    { term: 'Cloud vs on-premise', meaning: 'Cloud (SaaS) ERPs run on the vendor’s servers with a subscription; on-premise ERPs run on the company’s own servers.' },
    { term: 'ERP products for SMEs', meaning: 'Odoo and ERPNext (open source, modular), Microsoft Dynamics 365 Business Central, SAP Business One, Oracle NetSuite, Sage. Large enterprises often use SAP S/4HANA or Oracle. The concepts in this course apply to all of them.' },
  ],
  integrations: [
    { module: 'Sales → Inventory', how: 'A confirmed sales order creates a delivery order for the warehouse.' },
    { module: 'Inventory → Accounting', how: 'Each validated stock movement posts a stock valuation entry.' },
    { module: 'Sales → Accounting', how: 'Invoices are journal entries: revenue, VAT and receivable.' },
    { module: 'Purchasing → Inventory', how: 'A confirmed purchase order creates a receipt.' },
    { module: 'Manufacturing → Inventory', how: 'Producing consumes components and adds finished goods.' },
    { module: 'HR → Accounting', how: 'Payroll posts salary costs and the debts to employees and the state.' },
    { module: 'CRM → Sales', how: 'An opportunity turns into a quotation without retyping.' },
  ],
  bestPractices: [
    'Enter data once, at the source, by the person who owns it.',
    'Adapt processes to the ERP’s standard flows where possible; customise only when there is a real business reason.',
    'Keep master data clean: it drives every document.',
    'Use the ERP’s documents and states instead of side spreadsheets, or the single source of truth is lost.',
  ],
  mistakes: [
    'Recreating the old spreadsheets inside the ERP instead of using its standard documents.',
    'Over-customising: every customisation must be maintained and tested at every upgrade.',
    'Letting each department configure its part alone. Integration only works when the whole flow is designed together.',
  ],
  tryIt: [
    { label: 'ERP Map: watch one order flow through every module', to: '/learn' },
    { label: 'Dashboard', to: '/' },
  ],
  scenarios: ['sell'],
  quiz: [
    { q: 'What is the main problem an ERP solves?', options: ['Slow computers', 'Information silos: the same data typed several times in different tools', 'Lack of email', 'Website design'], answer: 1, why: 'An ERP replaces disconnected tools with one shared database so data is entered once and is consistent everywhere.' },
    { q: 'Which one is master data?', options: ['An invoice', 'A delivery order', 'A product', 'A payment'], answer: 2, why: 'Products rarely change and are reused by many transactions. Invoices, deliveries and payments are transactions.' },
    { q: 'The warehouse validates a delivery. What happens in Accounting?', options: ['Nothing until month-end', 'A stock valuation entry is posted automatically', 'The accountant must type it', 'The invoice is deleted'], answer: 1, why: 'Integration: the stock movement posts its cost entry immediately (perpetual inventory).' },
    { q: 'Who is usually the reference user of the ERP inside a department?', options: ['The developer', 'The key user', 'The CEO', 'The vendor'], answer: 1, why: 'Key users know the department’s process and are trained first; they support their colleagues.' },
  ],
}

export const masterData: Chapter = {
  slug: 'master-data',
  number: 2,
  title: 'Master Data',
  department: 'Foundations',
  icon: 'Database',
  color: 'teal',
  minutes: 15,
  summary: 'The “nouns” of the ERP: customers, vendors, products, accounts, taxes, employees. Every transaction points to them, so their quality decides the quality of everything else.',
  goals: [
    'List the main master data objects and their key fields',
    'Explain how master data fills documents automatically',
    'Understand product types and why they matter',
    'Know why data migration is critical in implementations',
  ],
  intro: [
    'Master data is the information that rarely changes and is reused by many transactions. When a salesperson picks a customer and a product, the ERP fills in the price, the tax, the payment terms, the delivery address and later the accounting accounts, all from master data.',
    'The golden rule: transactions point to master data. If a product’s cost is wrong, every margin report and every stock valuation entry will be wrong. That is why implementation projects spend so much time cleaning and importing master data.',
  ],
  concepts: [
    { term: 'Contact / Partner', meaning: 'One record for customers and vendors (Odoo’s res.partner). Holds address, tax ID, payment terms, credit limit, receivable and payable accounts.' },
    { term: 'Product', meaning: 'Reference (SKU), name, type, unit of measure, sale price, cost, taxes, category, barcode, reorder rule, main vendor.' },
    { term: 'Product type', meaning: 'Storable (quantity tracked and valued), Consumable (delivered but not counted precisely), Service (no stock).' },
    { term: 'Product category', meaning: 'Groups products and carries their accounting setup: income, cost of goods sold and stock valuation accounts.' },
    { term: 'Unit of measure (UoM)', meaning: 'How a product is counted (Unit, kg, Hour, Box of 10). Real ERPs convert between units of the same category.' },
    { term: 'Payment terms', meaning: 'When an invoice or bill is due (Immediate, 30 days, 50% upfront…).' },
    { term: 'Taxes', meaning: 'Rates and the accounts they post to (VAT collected → liability, VAT paid → reclaimable asset).' },
    { term: 'Chart of accounts', meaning: 'The list of accounting accounts, numbered by family (assets, liabilities, equity, income, expenses). Often defined by the country’s standard.' },
    { term: 'Price list', meaning: 'Different prices per customer group (retail, wholesale) or quantity. Not built in NexusERP, but standard in real ERPs.' },
  ],
  integrations: [
    { module: 'Sales', how: 'Customer, product price, sales tax, payment terms, credit limit.' },
    { module: 'Purchasing', how: 'Vendor, product cost, purchase tax, main vendor for replenishment.' },
    { module: 'Inventory', how: 'Product type, unit of measure, reorder point, barcode.' },
    { module: 'Accounting', how: 'Accounts on categories, taxes and contacts decide every automatic entry.' },
    { module: 'HR', how: 'Employees, departments and wages are HR’s master data.' },
  ],
  bestPractices: [
    'Assign an owner to each master data type (e.g. Sales owns customers, Purchasing owns vendors, Finance owns accounts).',
    'Use naming and code conventions (SKU format, customer names) and forbid duplicates.',
    'Set accounts on product categories, not product by product.',
    'Review master data before go-live: costs, taxes and units are the usual sources of errors.',
  ],
  mistakes: [
    'Duplicate customers (“ABC Corp” and “ABC Corporation”): split history and wrong credit control.',
    'Wrong or missing product costs: margins and stock value are wrong from day one.',
    'Wrong product type: a storable product created as consumable is never counted or valued.',
  ],
  consultant: {
    questions: ['How many customers, vendors and products are active?', 'Which system holds the reference data today?', 'Do you need several units of measure or price lists?', 'Which chart of accounts is legally required?'],
    data: ['Customers & vendors (address, tax ID, terms)', 'Products (SKU, type, UoM, price, cost, taxes, barcode)', 'Chart of accounts & taxes', 'Opening stock quantities and values', 'Open invoices and bills (opening balances)'],
    configure: ['Product categories with accounts', 'Taxes and fiscal positions', 'Payment terms', 'Units of measure', 'Sequences (document numbering)'],
  },
  tryIt: [
    { label: 'Contacts', to: '/contacts' },
    { label: 'Products (see the accounting box on a product)', to: '/products' },
    { label: 'Chart of Accounts', to: '/accounts' },
  ],
  quiz: [
    { q: 'A product’s cost is wrong. What is affected?', options: ['Only the product page', 'Margins and stock valuation entries', 'Nothing', 'Only taxes'], answer: 1, why: 'Cost drives cost of goods sold and inventory value in every entry.' },
    { q: 'Where should income and expense accounts usually be set?', options: ['On each invoice', 'On the product category', 'On the user', 'On the warehouse'], answer: 1, why: 'Categories carry the accounting setup so all their products post consistently.' },
    { q: 'Which product type has no stock at all?', options: ['Storable', 'Consumable', 'Service', 'Component'], answer: 2, why: 'Services are sold or bought but never stocked or delivered.' },
  ],
}
