import type { Chapter } from './types'

export const otherModules: Chapter = {
  slug: 'other-modules',
  number: 10,
  title: 'Beyond the Core',
  department: 'Extended ERP',
  icon: 'LayoutGrid',
  color: 'teal',
  minutes: 10,
  summary: 'The other apps an SME ERP usually offers, and how they plug into the core you now know.',
  goals: ['Recognise the extended modules clients ask about', 'Know which core module each one feeds'],
  intro: [
    'Full ERP suites offer many more apps around the core. They all reuse the same master data and post into the same accounting. When a client asks for one, ask which core flow it changes.',
  ],
  concepts: [
    { term: 'Point of Sale (POS)', meaning: 'Shop checkout. Creates sales, stock moves and cash/bank entries per session.' },
    { term: 'eCommerce / website', meaning: 'Online shop creating quotations or paid orders directly in Sales.' },
    { term: 'Projects & timesheets', meaning: 'Track tasks and hours; invoice time to customers or compute project cost.' },
    { term: 'Helpdesk', meaning: 'Customer support tickets, often linked to sales orders and returns.' },
    { term: 'Field service', meaning: 'Technicians on site; consumes parts from stock and invoices interventions.' },
    { term: 'Quality', meaning: 'Control points at receipt or production; failed checks block or scrap goods.' },
    { term: 'Maintenance', meaning: 'Preventive and corrective maintenance of equipment (often fixed assets).' },
    { term: 'Subscriptions', meaning: 'Recurring invoices (monthly/yearly plans).' },
    { term: 'Rental', meaning: 'Rent products out and back in, with deposits and late fees.' },
    { term: 'Fleet', meaning: 'Company vehicles: contracts, fuel, servicing costs.' },
    { term: 'Documents & e-signature', meaning: 'Store and sign contracts, quotations and HR documents.' },
    { term: 'Multi-company & multi-currency', meaning: 'Several legal entities and currencies in one database, with inter-company flows and exchange differences.' },
  ],
  integrations: [
    { module: 'POS, eCommerce, Subscriptions', how: 'Feed Sales and Accounting.' },
    { module: 'Field service, Rental, Quality', how: 'Feed Inventory.' },
    { module: 'Projects, Timesheets', how: 'Feed HR costs and customer invoices.' },
    { module: 'Maintenance, Fleet', how: 'Relate to Fixed Assets and expenses.' },
  ],
  bestPractices: ['Implement the core first; add extended modules once the core is stable.'],
  mistakes: ['Starting a project with the most exotic module while the basics are not yet running.'],
  quiz: [
    { q: 'A POS sale should update…', options: ['Only the cash drawer', 'Sales, stock and accounting', 'Only HR', 'Nothing'], answer: 1, why: 'POS is just another sales channel on top of the same core.' },
    { q: 'Billable hours are recorded with…', options: ['Timesheets', 'BoMs', 'Credit notes', 'Receipts'], answer: 0, why: 'Timesheets record time per project or task, then feed invoices.' },
  ],
}

export const implementation: Chapter = {
  slug: 'implementation',
  number: 11,
  title: 'ERP Implementation',
  department: 'Consulting',
  icon: 'Rocket',
  color: 'red',
  minutes: 30,
  summary: 'How an ERP project actually runs for a client: the phases, the people, the deliverables and the classic pitfalls.',
  goals: [
    'Know the phases of an implementation project',
    'Run a discovery workshop and write a fit-gap analysis',
    'Plan data migration, testing (UAT), training and go-live',
    'Avoid the most common causes of failed projects',
  ],
  intro: [
    'Most ERP failures are not software failures: they come from unclear scope, poor data, missing user involvement or too much customisation. A good functional consultant mostly asks questions, documents processes and makes sure the client’s people own the new system.',
    'Methods vary (waterfall, agile, vendor methodologies such as Odoo’s or SAP Activate), but the phases below appear in every project.',
  ],
  roles: [
    { name: 'Sponsor', does: 'Executive who owns the budget and makes final decisions.' },
    { name: 'Project manager (client & integrator)', does: 'Plan, scope, risks, communication.' },
    { name: 'Functional consultant', does: 'Workshops, fit-gap, configuration, training.' },
    { name: 'Developer', does: 'Customisations, integrations, data import scripts.' },
    { name: 'Key users', does: 'Represent each department, test, then train colleagues.' },
  ],
  process: [
    {
      title: 'Implementation phases',
      steps: [
        { label: '1. Discovery', doc: 'Process map', who: 'Consultant + key users', effect: 'Understand current processes, pains and goals' },
        { label: '2. Fit-gap', doc: 'Fit-gap analysis', who: 'Consultant', effect: 'Each requirement: standard fit, configuration, or gap (custom dev / workaround)' },
        { label: '3. Design & scope', doc: 'Solution design + plan', who: 'PM + consultant', effect: 'Signed scope, budget, timeline' },
        { label: '4. Configure & build', doc: 'Configured system', who: 'Consultant + developer', effect: 'Settings, master data structure, customisations' },
        { label: '5. Data migration', doc: 'Import files', who: 'Key users + developer', effect: 'Cleaned master data and opening balances loaded' },
        { label: '6. Testing (UAT)', doc: 'Test scripts & sign-off', who: 'Key users', effect: 'End-to-end scenarios pass with real data' },
        { label: '7. Training', doc: 'User guides', who: 'Consultant → key users → users', effect: 'Everyone can do their daily tasks' },
        { label: '8. Go-live & hypercare', doc: 'Cut-over plan', who: 'Everyone', effect: 'Switch systems; intensive support for the first weeks' },
      ],
    },
  ],
  concepts: [
    { term: 'As-is / to-be', meaning: 'How processes work today vs. how they will work in the ERP.' },
    { term: 'Fit-gap analysis', meaning: 'For each requirement: covered by standard, by configuration, or a gap needing development or a process change.' },
    { term: 'Scope creep', meaning: 'Uncontrolled growth of requirements during the project. Managed with change requests.' },
    { term: 'Data migration', meaning: 'Extract, clean, map and import master data and opening balances (open invoices, stock, trial balance).' },
    { term: 'Cut-over', meaning: 'The precise plan to stop the old system and start the new one (freeze, final imports, checks).' },
    { term: 'UAT', meaning: 'User Acceptance Testing: key users run real scenarios and sign off.' },
    { term: 'Hypercare', meaning: 'The first weeks after go-live with reinforced support.' },
    { term: 'Train-the-trainer', meaning: 'Consultants train key users, who train the rest of their department.' },
    { term: 'Change management', meaning: 'Helping people accept new ways of working: communication, training, involvement.' },
  ],
  bestPractices: [
    'Start every workshop with the end-to-end process (e.g. O2C), not with screens.',
    'Prefer standard processes; every customisation must have a clear business value.',
    'Make the client own data cleaning: only they know which customers and products are real.',
    'Test with real data and complete scenarios, not single screens (the guided scenarios in this app are good UAT examples).',
    'Plan go-live outside peak season and avoid month-end or year-end.',
    'Document decisions and get sign-offs at the end of each phase.',
  ],
  mistakes: [
    'Copying the old system feature by feature into the new ERP.',
    'Underestimating data migration: dirty data is the number-one cause of go-live problems.',
    'Key users without time allocated to the project.',
    'Skipping UAT or training to keep the date.',
    'Going live without a cut-over plan and rollback criteria.',
  ],
  consultant: {
    questions: [
      'What are the 3 biggest pains today?',
      'Walk me through an order from first contact to cash.',
      'Which reports does management use to decide?',
      'Which other systems must connect (bank, e-commerce, e-invoicing, payroll provider)?',
      'Who will be the key user for each department, and how much time can they give?',
      'What is the go-live constraint (date, season, fiscal year)?',
    ],
    data: ['Customers, vendors, products', 'Chart of accounts & opening trial balance', 'Open sales/purchase orders', 'Open invoices and bills', 'Stock quantities and values', 'Employees and contracts', 'Fixed asset register'],
    configure: ['Company, users and access rights', 'Each module following the fit-gap', 'Document templates', 'Sequences and lock dates', 'Integrations'],
  },
  tryIt: [
    { label: 'Use the guided scenarios as UAT test scripts', to: '/scenarios' },
    { label: 'Glossary', to: '/glossary' },
  ],
  scenarios: [],
  quiz: [
    { q: 'What does a fit-gap analysis produce?', options: ['The invoice template', 'For each requirement: standard, configuration or gap', 'The payroll', 'The logo'], answer: 1, why: 'It classifies requirements to decide scope and effort.' },
    { q: 'The most common cause of go-live problems is…', options: ['Screen colours', 'Poor data quality', 'Too many users', 'Fast servers'], answer: 1, why: 'Dirty master data and wrong opening balances break documents and reports.' },
    { q: 'Who should test the system before go-live?', options: ['Only the developer', 'Key users with real scenarios (UAT)', 'Nobody', 'The vendor’s sales team'], answer: 1, why: 'Key users know the business and must sign off.' },
    { q: 'When is a good go-live date?', options: ['The last day of the fiscal year', 'During the busiest season', 'A calm period, at the start of a month', 'Friday evening before holidays'], answer: 2, why: 'Starting at a period start with calm activity simplifies cut-over and support.' },
  ],
}
