# Generated by Django 5.2.17 on 2026-10-02 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_move_reversed_entry_alter_move_move_type'),
        ('masterdata', '0002_product_purchase_tax_product_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Purchase value')),
                ('acquisition_date', models.DateField(default=django.utils.timezone.localdate)),
                ('useful_life_months', models.PositiveIntegerField(default=60)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('running', 'Depreciating'), ('closed', 'Fully depreciated')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Fixed-asset account where the purchase is recorded.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.move')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masterdata.partner')),
            ],
            options={
                'ordering': ['-acquisition_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.move')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fixedassets.fixedasset')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
