# Generated by Django 5.2.17 on 2026-10-02 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('days', models.PositiveIntegerField(default=0, help_text='Days after invoice date the payment is due.')),
            ],
            options={
                'ordering': ['days'],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_company', models.BooleanField(default=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_vendor', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('street', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('vat', models.CharField(blank=True, max_length=32, verbose_name='Tax ID')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='0 = no limit.', max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('receivable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.paymentterm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('expense_account', models.ForeignKey(help_text='Debited when the product leaves stock (cost of goods sold).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('income_account', models.ForeignKey(help_text='Credited when the product is invoiced (revenue).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
                ('stock_valuation_account', models.ForeignKey(help_text='Asset account holding the value of goods in the warehouse.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account')),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage, e.g. 20 for 20%.', max_digits=6)),
                ('scope', models.CharField(choices=[('sale', 'Sales'), ('purchase', 'Purchases')], default='sale', max_length=16)),
                ('account', models.ForeignKey(help_text='Where collected/paid tax is booked (a liability for sales tax).', on_delete=django.db.models.deletion.PROTECT, related_name='taxes', to='accounting.account')),
            ],
            options={
                'verbose_name_plural': 'taxes',
                'ordering': ['scope', 'rate'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True, verbose_name='Internal reference')),
                ('name', models.CharField(max_length=128)),
                ('product_type', models.CharField(choices=[('storable', 'Storable'), ('consumable', 'Consumable'), ('service', 'Service')], default='storable', max_length=16)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('reorder_min', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='masterdata.productcategory')),
                ('sale_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masterdata.tax')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.unitofmeasure')),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
    ]
