# Generated by Django 5.2.17 on 2026-10-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masterdata.tax'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Main supplier, used by replenishment to draft RFQs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='masterdata.partner'),
        ),
    ]
