# Generated by Django 5.2.17 on 2026-10-02 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0002_product_purchase_tax_product_vendor'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="What the prospect wants, e.g. 'Furnish new office'.", max_length=128)),
                ('contact_name', models.CharField(blank=True, max_length=128)),
                ('company_name', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(blank=True, help_text='Website, referral, trade show…', max_length=32)),
                ('expected_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('probability', models.PositiveIntegerField(default=10)),
                ('stage', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('proposition', 'Proposition'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=16)),
                ('lost_reason', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='masterdata.partner')),
                ('sale_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='sales.saleorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
