# Generated by Django 5.2.17 on 2026-10-02 06:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('usage', models.CharField(choices=[('internal', 'Internal'), ('customer', 'Customer'), ('supplier', 'Vendor'), ('inventory', 'Inventory Adjustment')], max_length=16)),
            ],
            options={
                'ordering': ['usage', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Picking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('incoming', 'Receipt'), ('outgoing', 'Delivery Order'), ('adjustment', 'Inventory Adjustment')], max_length=16)),
                ('state', models.CharField(choices=[('ready', 'Ready'), ('done', 'Done'), ('cancel', 'Cancelled')], default='ready', max_length=16)),
                ('origin', models.CharField(blank=True, help_text='Source document, e.g. S00004.', max_length=64)),
                ('scheduled_date', models.DateField(default=django.utils.timezone.localdate)),
                ('date_done', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dest_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.location')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickings', to='masterdata.partner')),
                ('sale_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickings', to='sales.saleorder')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.location')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('state', models.CharField(choices=[('ready', 'Ready'), ('done', 'Done'), ('cancel', 'Cancelled')], default='ready', max_length=16)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('dest_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves_in', to='inventory.location')),
                ('picking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='inventory.picking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='masterdata.product')),
                ('sale_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves', to='sales.saleorderline')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves_out', to='inventory.location')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='inventory.warehouse'),
        ),
    ]
