# Generated by Django 5.2.17 on 2026-10-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_move_production_move_purchase_order_and_more'),
        ('inventory', '0001_initial'),
        ('mrp', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picking',
            name='counterpart_account',
            field=models.ForeignKey(blank=True, help_text='Overrides the account balancing the stock valuation entry (e.g. equity for opening stock).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='picking',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickings', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='mrp.manufacturingorder'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='purchase_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves', to='purchase.purchaseorderline'),
        ),
        migrations.AlterField(
            model_name='location',
            name='usage',
            field=models.CharField(choices=[('internal', 'Internal'), ('customer', 'Customer'), ('supplier', 'Vendor'), ('inventory', 'Inventory Adjustment'), ('production', 'Production')], max_length=16),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='picking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='inventory.picking'),
        ),
    ]
