# Generated by Django 5.2.17 on 2026-10-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_picking_counterpart_account_picking_purchase_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picking',
            name='kind',
            field=models.CharField(choices=[('incoming', 'Receipt'), ('outgoing', 'Delivery Order'), ('adjustment', 'Inventory Adjustment'), ('return', 'Customer Return')], max_length=16),
        ),
    ]
