# Generated by Django 5.2.17 on 2026-10-02 11:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0002_product_purchase_tax_product_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, help_text='Quantity this recipe produces.', max_digits=12)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='masterdata.product')),
            ],
            options={
                'verbose_name_plural': 'bills of materials',
                'ordering': ['product__sku'],
            },
        ),
        migrations.CreateModel(
            name='BomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='mrp.billofmaterials')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('done', 'Done'), ('cancel', 'Cancelled')], default='draft', max_length=16)),
                ('origin', models.CharField(blank=True, max_length=64)),
                ('date_planned', models.DateField(default=django.utils.timezone.localdate)),
                ('date_done', models.DateTimeField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit produced (sum of components).', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='mrp.billofmaterials')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
