# Generated by Django 5.2.17 on 2026-10-02 11:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0002_product_purchase_tax_product_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('state', models.CharField(choices=[('draft', 'RFQ'), ('purchase', 'Purchase Order'), ('cancel', 'Cancelled')], default='draft', max_length=16)),
                ('date_order', models.DateField(default=django.utils.timezone.localdate)),
                ('date_planned', models.DateField(blank=True, help_text='Expected arrival of the goods.', null=True)),
                ('note', models.TextField(blank=True)),
                ('amount_untaxed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='masterdata.partner')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.paymentterm')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=256)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('price_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('qty_received', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('qty_billed', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.product')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.tax')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
